/** @type {import('tailwindcss').Config} */
export default {
  content: ["./*.html", "./src/**/*.{js,ts,jsx,tsx,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2a1700",
        "surface-container-low": "#171c20",
        "inverse-primary": "#00668a",
        "surface-container-highest": "#303539",
        "secondary-fixed": "#d4e4fa",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed-variant": "#39485a",
        "on-primary-fixed-variant": "#004c69",
        "tertiary-fixed-dim": "#ffb960",
        "primary-container": "#38bdf8",
        "outline-variant": "#3e484f",
        "on-tertiary": "#472a00",
        primary: "#8ed5ff",
        "surface-container-lowest": "#0a0f12",
        "on-background": "#dee3e8",
        surface: "#0f1418",
        "on-tertiary-container": "#613b00",
        "surface-bright": "#343a3e",
        "primary-fixed": "#c4e7ff",
        "surface-variant": "#303539",
        "error-container": "#93000a",
        outline: "#87929a",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#b9c8de",
        "on-secondary-container": "#a7b6cc",
        "on-primary": "#00354a",
        "on-error": "#690005",
        "surface-tint": "#7bd0ff",
        tertiary: "#ffc176",
        "primary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#0d1c2d",
        "on-primary-container": "#004965",
        "inverse-on-surface": "#2c3135",
        secondary: "#b9c8de",
        "surface-container-high": "#252b2e",
        error: "#ffb4ab",
        "tertiary-container": "#f1a02b",
        "secondary-container": "#39485a",
        "on-secondary": "#233143",
        "inverse-surface": "#dee3e8",
        background: "#0f1418",
        "surface-container": "#1b2024",
        "surface-dim": "#0f1418",
        "on-surface-variant": "#bdc8d1",
        "on-primary-fixed": "#001e2c",
        "on-surface": "#dee3e8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "margin-page": "40px",
        gutter: "24px",
        "container-max": "1280px",
        unit: "4px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        h1: ["Space Grotesk", "sans-serif"],
        h3: ["Space Grotesk", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        h2: ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": [
          "16px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
        h1: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        h3: [
          "24px",
          { lineHeight: "1.3", letterSpacing: "0", fontWeight: "500" },
        ],
        "label-sm": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        h2: [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
